### PR TITLE
Add Documentation for users to understand #8

### PR DESCRIPTION
**Pull request by Chaitanya31612**
Improved documentation.

### CODE REVIEW

**Review by shelcia — CHANGES_REQUESTED** [review]
There are more changes to be added

**Comment by Chaitanya31612** [comment]
> There are more changes to be added

Sure thing, Can you suggest what else should be done?

**Comment by shelcia** [comment]
> > There are more changes to be added
> 
> Sure thing, Can you suggest what else should be done?

like more explanation of the what each can do

**Comment by Chaitanya31612** [comment]
@shelcia please review my pull request now.

**Comment by Chaitanya31612** [comment]
@shelcia can you please review my PR and suggest if anything else needs to be done.

**Review by shelcia — APPROVED** [review]

**Pull request merged**
